CREATE TABLE IF NOT EXISTS media (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	description TEXT NOT NULL,
	media_type TEXT NOT NULL,
	rating FLOAT,
	notes TEXT,
	related_link TEXT,
	cart BOOLEAN NOT NULL,
	completed BOOLEAN NOT NULL,
	progress FLOAT NOT NULL,
	completed_date TIMESTAMP(0),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS todos (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	description TEXT NOT NULL,
	private BOOLEAN NOT NULL DEFAULT false,
	cart BOOLEAN NOT NULL,
	completed BOOLEAN NOT NULL,
	progress FLOAT NOT NULL,
	due_date TIMESTAMP(0),
	completed_date TIMESTAMP(0),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS feedsource {
	id BIGSERIAL PRIMARY KEY NOT NULL,
	url TEXT NOT NULL
};
